DESCRIBE test.assignments;
use test;
DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID   INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(20),
    DEPARTMENT    VARCHAR(20),
    PROJECT       VARCHAR(20),
    PERFORMANCE   INT
);

INSERT INTO EMPLOYEES
VALUES (1, 'ANANTH', 'IT', 'SPRING', 100),
       (2, 'BHAGATH', 'SALES', 'SPRING', 78),
       (3, 'CHAYA', 'MARKETING', 'MACHINE_LEARNING', 68),
       (4, 'ESHARATH', 'FINANCE', 'SPRING', 87),
       (5, 'BHAGATH', 'SALES', 'MACHINE_LEARNING', 20),
       (6, 'CHAYA', 'MARKETING', 'JAVA', 10),
       (7, 'ANANTH', 'IT', 'JAVA', 100),
       (8, 'DAVANTH', 'FINANCE', 'MACHINE_LEARNING', 100),
       (9, 'BHAGATH', 'SALES', 'JAVA', 50),
       (10, 'ANANTH', 'IT', 'MACHINE_LEARNING', 100),
       (11, 'BHAGATH', 'SALES', 'CLOUD', 10),
       (12, 'CHAYA', 'MARKETING', 'CLOUD', 100),
       (13, 'BHAGATH', 'SALES', 'DEVOPS', 100),
       (14, 'DAVANTH', 'FINANCE', 'CLOUD', 86),
       (15, 'ANANTH', 'IT', 'CLOUD', 100),
       (16, 'BHAGATH', 'SALES', 'MIGRATION', 100),
       (17, 'ANANTH', 'IT', 'DEVOPS', 100),
       (18, 'CHAYA', 'MARKETING', 'DEVOPS', 20),
       (19, 'ANANTH', 'IT', 'MIGRATION', 80),
       (20, 'CHAYA', 'MARKETING', 'SPRING', 92);


USE test;

SELECT COUNT(*)
FROM test.assignments;

SELECT COUNT(*) AS COUNT
FROM test.assignments;


TRUNCATE TABLE test.assignments;

DROP TABLE test.assignments;


SELECT DISTINCT STUDENT_NAME
FROM assignments
ORDER BY STUDENT_NAME;


SELECT *
FROM assignments
WHERE STUDENT_NAME = 'ANANTH'
ORDER BY SUBJECT;

SELECT *
FROM assignments
WHERE SUBJECT = 'IT'
ORDER BY STUDENT_NAME, ASSIGNMENT_CATEGORY;


SELECT *
FROM assignments
WHERE STUDENT_NAME = 'CHAYA'
  AND SUBJECT = ''
  AND ASSIGNMENT_CATEGORY = 'QUIZ_1';

UPDATE assignments
SET POINTS = 21
WHERE STUDENT_NAME = 'CHAYA'
  AND SUBJECT = ''
  AND ASSIGNMENT_CATEGORY = 'QUIZ_1';


UPDATE assignments
SET STUDENT_NAME = 'ANANTH'
WHERE SERIAL_NO IN (SELECT SERIAL_NO WHERE STUDENT_NAME = 'A');

DELETE
FROM assignments
WHERE SUBJECT = ?
  AND POINTS < ?;

DELETE
FROM assignments
WHERE STUDENT_NAME = 'ANANTH'
  AND ASSIGNMENT_CATEGORY LIKE 'TEST%';
