USE test;
TRUNCATE TABLE test.assignments;

INSERT INTO ASSIGNMENTS
VALUES (1, 'ANANTH', 'ELECTRO_FIELDS', 'TEST_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (2, 'BHAGATH', 'ELECTRO_FIELDS', 'TEST_1', 78);
INSERT INTO ASSIGNMENTS
VALUES (3, 'CHAYA', 'ELECTRO_FIELDS', 'TEST_1', 68);
INSERT INTO ASSIGNMENTS
VALUES (4, 'ESHARATH', 'ELECTRO_FIELDS', 'TEST_1', 87);
INSERT INTO ASSIGNMENTS
VALUES (5, 'BHAGATH', 'ELECTRO_FIELDS', 'QUIZ_1', 20);
INSERT INTO ASSIGNMENTS
VALUES (6, 'CHAYA', 'ELECTRO_FIELDS', 'LAB_1', 10);
INSERT INTO ASSIGNMENTS
VALUES (7, 'ANANTH', 'ELECTRO_FIELDS', 'PROJECT_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (8, 'DAVANTH', 'ELECTRO_FIELDS', 'PROJECT_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (9, 'BHAGATH', 'ELECTRO_FIELDS', 'QUIZ_2', 50);
INSERT INTO ASSIGNMENTS
VALUES (10, 'ANANTH', 'ELECTRO_FIELDS', 'QUIZ_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (11, 'BHAGATH', 'ELECTRO_FIELDS', 'LAB_1', 10);
INSERT INTO ASSIGNMENTS
VALUES (12, 'CHAYA', 'ELECTRO_FIELDS', 'PROJECT_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (13, 'BHAGATH', 'ELECTRO_FIELDS', 'PROJECT_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (14, 'ANANTH', 'COMPUTING_TECHNIQUES', 'TEST_1', 86);
INSERT INTO ASSIGNMENTS
VALUES (15, 'ANANTH', 'ELECTRO_FIELDS', 'QUIZ_2', 100);
INSERT INTO ASSIGNMENTS
VALUES (16, 'BHAGATH', 'COMPUTING_TECHNIQUES', 'PROJECT_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (17, 'ANANTH', 'ELECTRO_FIELDS', 'LAB_1', 100);
INSERT INTO ASSIGNMENTS
VALUES (18, 'CHAYA', 'COMPUTING_TECHNIQUES', 'QUIZ_1', 20);
INSERT INTO ASSIGNMENTS
VALUES (19, 'ANANTH', 'ELECTRO_FIELDS', 'TEST_2', 80);
INSERT INTO ASSIGNMENTS
VALUES (20, 'CHAYA', 'ELECTRO_FIELDS', 'TEST_2', 92);
